### ISSUE TITLE
Close specific WebSocket API Gateway connection.

### ISSUE THREAD

**Issue by JoseRolles** [aws-samples/simple-websockets-chat-app#10]
How do we close a specific WebSocket API Gateway client connection from the server side?

**Comment by JoseRolles** [comment]
Documentation at the following link says it is possible to close a connection from the backend by using @connections endpoint. It points to another documentation page which mentions nothing about closing a connection from the backend:
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-keys-connect-disconnect.html

Also, I checked the JavaScript SDK reference and the only method is postToConnection without any mention of disconnecting the connectionId.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ApiGatewayManagementApi.html

**Comment by dgomesbr** [comment]
@JoseRolles using ```@connections```, DELETE to it should disconnect the client.

**Comment by knopp** [comment]
Perhaps the documentation could be updated so that people don't need to search github issues for answers?

**Comment by kkirov** [comment]
Use DeleteConnectionCommand - https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-apigatewaymanagementapi/classes/deleteconnectioncommand.html
