### ISSUE TITLE
Error while loading API Gateway Management API

### ISSUE THREAD

**Issue by writerofsorts** [aws-samples/simple-websockets-chat-app#11]
While running the Lambda function sendmessage on AWS west-2; got the following error:

const AWS = require('aws-sdk');
// Add ApiGatewayManagementApi to the AWS namespace
require('aws-sdk/clients/apigatewaymanagementapi');

{
  "errorMessage": "Cannot find module 'aws-sdk/clients/apigatewaymanagementapi'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:474:25)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/index.js:7:1)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)"
  ]
Is ApiGatewayManagementApi not part of SDK version in Oregon?

**Comment by writerofsorts** [comment]
Found the error. Not an issue

**Comment by writerofsorts** [comment]
Closed

**Comment by pankesh** [comment]
@writerofsorts could u share what you found. I'm seeing the same issue
