### ISSUE TITLE
Request: Provide documentation for `sam local`

### ISSUE THREAD

**Issue by tylers-username** [aws-samples/simple-websockets-chat-app#14]
I'm attempting to test this repository local with `sam local start-lambda --region us-east1`, which spins up at 127.0.0.1:3001. However, any attempt to connect to to this path wtih `wss://` or `ws://` returns "Bad Request" within the SAM output.

It would be great if testing documentation could be added to the repository.

**Comment by dgomesbr** [comment]
Thanks for the feedback Tyler, looks like SAM doesn't support wss just yet. https://github.com/awslabs/aws-sam-cli/issues/896

**Comment by dgomesbr** [comment]
I'm closing this one as it's being handled on the aws-sam-cli project.
