### ISSUE TITLE
Keep SAR app up to date with latest changes

### ISSUE THREAD

**Issue by jlhood** [aws-samples/simple-websockets-chat-app#17]
This app has been modified in GitHub, but those updates haven't been published to SAR. Deploying the app via SAR is a much simpler experience than using GitHub and SAM CLI. SAR has some features that launched since this app was released that should help you keep this app in sync.

SAM CLI added a `sam publish` command that allows you to specify the SAR metadata of the app in the template itself. This will allow you to follow best practices like including the GitHub URL for the app and sourceCodeUrls, for example. Then you can run `sam publish`.

Opening an issue to add SAR metadata and use either `sam publish` or the new CodePipeline app to make sure the SAR app stays in sync with changes made to this GitHub repo.

* sam publish docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-publish.html
* SAR metadata docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications-metadata-properties.html
* Example app metadata: https://github.com/jlhood/github-codebuild-logs/blob/master/template.yml#L7-L24
* CodePipeline tutorial for automatic publishing to SAR: https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-serverlessrepo-auto-publish.html

**Comment by jt0** [comment]
Updated.
