### ISSUE TITLE
SendMessage import error

### ISSUE THREAD

**Issue by armujahid** [aws-samples/simple-websockets-chat-app#18]
SendMessage lamda function is throwing exception if I send this message:
`{"message":"sendMessage", "data":"hello world"}`
![image](https://user-images.githubusercontent.com/3725386/55249088-1a707000-526d-11e9-9b69-1b03cc23c9b6.png)

I deployed it directly using [serverless repo](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:729047367331:applications~simple-websockets-chat-app) and haven't changed a single line of code.

**Cloudwatch logs:**
![image](https://user-images.githubusercontent.com/3725386/55248257-3bd05c80-526b-11e9-8e6f-440fbbc00f5b.png)

**Complete logs:**
```
START RequestId: 041b19b4-8d3f-4247-8d4c-16ba493b7b0f Version: $LATEST
Unable to import module 'app': Error
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/aws-sdk/clients/apigatewaymanagementapi.js:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
END RequestId: 041b19b4-8d3f-4247-8d4c-16ba493b7b0f
REPORT RequestId: 041b19b4-8d3f-4247-8d4c-16ba493b7b0f	Duration: 1.85 ms	Billed Duration: 100 ms 	Memory Size: 256 MB	Max Memory Used: 84 MB	
```
This error is related to `require('aws-sdk/clients/apigatewaymanagementapi');`
"aws-sdk": "^2.404.0" is already present in dependencies so I don't know why this is happening.

**Comment by astro21** [comment]
Here is what I did to fix this issue:

1. Go to Lambda console and export this serverlessrepo-simple-websocke-SendMessageFunction-xxxx function as a deployment package

2. Unzip the downloaded deployment package

3. Open a terminal and go the the folder of the deployment package

4. Install the aws-sdk

npm install aws-sdk

5. Zip the content of the folder and make sure app.js file is at the root level of the zipped file. This is your new deployment package

6. Upload your deployment package to your Lambda function.

**Comment by armujahid** [comment]
@astro21 thanks. I didn't know that aws lambda doesn't automatically run `npm install` after deployment. Since other two lambdas were working fine and SendMessage lambda already had `npm_modules` directory I incorrectly assumed that dependencies were being installed.

**Comment by dgomesbr** [comment]
That was an early dependency node_modules folder, not anymore. Now you should be able to do it.

**Comment by tomellis** [comment]
The latest code still refers to:
require('aws-sdk/clients/apigatewaymanagementapi');
which will fail as that no longer exists, commenting out this part fixes it for me but this needs to be removed from the app.js in the release.

**Comment by markotitel** [comment]
@tomellis 
Simply commenting the `require('aws-sdk/clients/apigatewaymanagementapi');` solves the issue for you?
Strange, if I just comment that part out the error is `AWS.ApiGatewayManagementApi is not a constructor`
Is this the answer? https://github.com/aws/aws-sdk-js/issues/2520#issuecomment-476723105

**Comment by markotitel** [comment]
What helped me is change NodeJS version to 10.x, with commented `require('aws-sdk/clients/apigatewaymanagementapi');`
I will try do to my first PR to see if I can do it properly and to see if this is proper programatic solution.

EDIT: Hope I have properly followed contribution guide.
https://github.com/aws-samples/simple-websockets-chat-app/pull/25
