### ISSUE TITLE
Client samples mentioned in blog are no longer valid.

### ISSUE THREAD

**Issue by tomellis** [aws-samples/simple-websockets-chat-app#19]
Client samples mentioned in [blog](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/) are no longer valid.

1. In the blog we have `$request.body.action` as route selection expression while latest code in this repo has `$request.body.message` as route selection expression. 
2. Correct route for message sending is `sendMessage`, not `sendmessage` as mentioned in blog post.

![image](https://user-images.githubusercontent.com/3725386/55247586-d760cd80-5269-11e9-8c4b-425f422b7458.png)

_Originally posted by @armujahid in https://github.com/aws-samples/simple-websockets-chat-app/issues/6#issuecomment-478068306_

**Comment by dgomesbr** [comment]
Thanks Tom, I've merged your PRs. I'll probably review the blog post again or put a disclaimer over there once I'm back from paternity leave.

**Comment by dgomesbr** [comment]
SAR application published (v. 1.0.3) to mirror the changes made to the repo
