### ISSUE TITLE
Unable to import module 'app'

### ISSUE THREAD

**Issue by onerider** [aws-samples/simple-websockets-chat-app#23]
So I simply deployed this code with no changes whatsoever. I can get a connection with no issues but when calling sendMessage I get an internal error. Looking in Cloudwatch, I see this error:

Unable to import module 'app': Error
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

**Comment by mwalker638** [comment]
I am also seeing the same thing.

**Comment by markotitel** [comment]
@mwalker638 @onerider 
https://github.com/aws-samples/simple-websockets-chat-app/issues/18

**Comment by dgomesbr** [comment]
Dup of #24
