### ISSUE TITLE
$disconnect is not called when connection goes down

### ISSUE THREAD

**Issue by ngPati** [aws-samples/simple-websockets-chat-app#27]
I have an app which uses redis to hold socketIds. Everytime when user leaves the site, $disconnect function is called in lambda and user is being removed from cache and something is logged to CloudWatch where I can check if function was called. 

Unfortunately when I turn off the internet connection on client (browser/PWA), the $disconnect lambda is not triggered :( 

how could this be possible?

**Comment by XJIOP** [comment]
you need implement ping pong function like a heartbeat

**Comment by dgomesbr** [comment]
Hello @ngPati as documented, $disconnect is a best effort event.

https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-keys-connect-disconnect.html

**Comment by Keerat-Grewal** [comment]
> Hello @ngPati as documented, $disconnect is a best effort event.
> 
> 
> 
> https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-route-keys-connect-disconnect.html
> 
> 
> 
> 

How would you go about dealing with disconnections from internet connection loss? Is there a way to create a ping/pong mechanism with aws websockets, if so how would you do that
