### ISSUE TITLE
Adding new routes after initial AWS CLI deployment are not recognised

### ISSUE THREAD

**Issue by acahinton** [aws-samples/simple-websockets-chat-app#28]
I have followed the instructions and used the AWS CLI to deploy the application - everything works fine - however, if you add a new route everything appears to have been created but API Gateway returns a forbidden message.

The only solution is to delete the stack and then re-run via the AWS CLI - the new route then works fine.

This may well be a Cloudformation issue or maybe someone can point me in the right direction. To create a new route I simply did the following:

 - copy the sendmessage folder as sendmessagedupe and update the name in the package.json
 - create a new route and integration in the resources section of the template with name and properties set appropriately
 - add the route to the deployment -> dependson list
 - create a new function and permission in the resources section of the template with name and properties set appropriately

(mirroring all the sections required by the original send message route and function)

As I say, deleting and recreating the stack then works so perhaps a AWS CLI/Cloudformation issue but not a workable solution as the stack is then created with a new url.

**Comment by acahinton** [comment]
Manually re-deploying the API to the Prod stage adds the new route correctly... I'll need to read a bit around that to get it working with the template to automate this.

**Comment by maustinstar** [comment]
Experiencing the same issue still. Any updates or insights?
