### ISSUE TITLE
Still running node 8

### ISSUE THREAD

**Issue by kennyk65** [aws-samples/simple-websockets-chat-app#34]
I see that the code in this repo has been updated to use node 10 and then node 12, but the link in this article (https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/) deploys node 8 - and fails.

**Comment by sfraise** [comment]
I'm having this problem as well, is there an updated version somewhere?

**Comment by NickFritz1982** [comment]
Looking for an updated version?

**Comment by sfraise** [comment]
Good working examples using API Gateway with Websockets are extremely lacking.  Would be nice if at least the official examples put out by Amazon worked.

**Comment by dgomesbr** [comment]
Hello folks, Post was last updated in 2018. I'm on leave, as soon as I'm back I'll clean the issues, plus push an update to the blog post!

**Comment by sfraise** [comment]
> Hello folks, Post was last updated in 2018. I'm on leave, as soon as I'm back I'll clean the issues, plus push an update to the blog post!

That would be outstanding, thank you!

We need to rebuild our existing traditional REST API into the API Gateway with websockets before moving on to new feature builds and are stalled out until we get our heads wrapped around this new stack/setup.  Having a real working example we can pick through like this will get us over the hump and let us start laying the foundation, and from there get back to rapid development on new stuff.

**Comment by dgomesbr** [comment]
Hello folks, I've updated the SAR (https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:729047367331:applications~simple-websockets-chat-app) to 1.0.3, which mirrors the latest changes in this repo.

I've also reverted the `RouteSelectionExpression` to `$request.body.action` to match the Blog post. 

Thanks for the continued patience on this one.

**Comment by sfraise** [comment]
I still can't even deploy it, it just says "is in ROLLBACK_COMPLETE state and can not be updated".

If there's some permissions or capability thing I'm missing I wouldn't know I guess as there's really not much for instructions or information anywhere.  Docs would make useful toilet paper I guess if you printed them out.

Using the API Gateway with websockets sounds like an ideal solution for our build if we could actually figure out how to use it but we've been spinning wheels for too long at this point.  If we can't even deploy a simple demo then there's no hope at all of figuring out how to actually build with it.
