### ISSUE TITLE
Possible rollback with version 1.0.3

### ISSUE THREAD

**Issue by dgomesbr** [aws-samples/simple-websockets-chat-app#36]
Reported on twitter: 

> "It’s reporting that “it is in a rollback_complete state and cannot be updated”. This is happening even in a region that I haven’t attempted a deployment."

by using a IAM user with correct permissions, I was able to deploy in a different region that my default one. "famous works on my machine"

![Stack deployed](https://i.imgur.com/6vUpdDw.png)

**Comment by sborsay** [comment]
ill keep working on it.  I shouldn't have any IAM issues as im the SU
