### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by kaihendry** [aws-samples/simple-websockets-chat-app#37]
Hi, my use case is to show a field to all people connected via HTML. If it updates, it needs to reflect on everyone's page. Is this a good starting point, or should I be looking at GraphQL?

Little puzzled why you don't have an HTML interface in your sample here.

**Comment by dgomesbr** [comment]
Hello @kaihendry, if you're looking more into a chat application, maybe amplify is more suitable for you https://aws.amazon.com/blogs/mobile/building-a-serverless-real-time-chat-application-with-aws-appsync/
