### ISSUE TITLE
postToConnection: No method found matching route

### ISSUE THREAD

**Issue by Ady88w1** [aws-samples/simple-websockets-chat-app#40]
When calling the sendmessage Lambda function, the following line:
await apigwManagementApi.postToConnection({ ConnectionId: connectionId, Data: postData }).promise();

returns an error:
No method found matching route test0/@connections/PxWP8cfSDoECFYw= for http method POST.

The connection ID is that of the caller, so should be able to mirror the message back to the caller.

Is this just a permissions issue, maybe the account calling the function doesn't have permission to post the the connection endpoint.

**Comment by dgomesbr** [comment]
Hey @Ady88w1, can you provide the steps to reproduce this?

**Comment by Ady88w1** [comment]
Hey @dgomesbr thanks for the reply. Because I had mapped the gateway api to a custom domain, using a default stage I needed to also change the endpoint parameter of the API initialization, so it now reads (removing event.requestContext.stage):

    const apigwManagementApi = new AWS.ApiGatewayManagementApi({
      apiVersion : '2018-11-29', 
      endpoint   : event.requestContext.domainName + '/'
    });
