### ISSUE TITLE
Stale connection not being detected

### ISSUE THREAD

**Issue by mustafapc19** [aws-samples/simple-websockets-chat-app#44]
There is section of code where the 'stale' connection is detected. 
This is the code snippet. I am not using the `Promise.all` that u guys are using if it does affect in anyway. Just calling await normally. And the value of `apiRes` here is {}, without erroring out Is there any work around to this? Because now sometimes my messages goes into unknown darkness :(

```
      try {
        var apiRes = await apigwManagementApi.postToConnection({
          ConnectionId: connectionId,
          Data: JSON.stringify(sockBody.data)
        }).promise();
        console.log('apiRes',apiRes);
      } catch (e) {
        console.log('apigwManagementApi.postToConnection:catch:',e);
      }
```

**Comment by dgomesbr** [comment]
Hello mustafapc19, API Gateway will do its best effort to detect and emit an event.
