### ISSUE TITLE
CORs error when trying to connect from client side with Socket.io

### ISSUE THREAD

**Issue by paul-uz** [aws-samples/simple-websockets-chat-app#45]
As per the title, I have created a super simple script to connect to the wss:// endpoint provided, using socket.io

```
const socket = io('wss://<app_id>.execute-api.<region>.amazonaws.com/<stage_name>');
socket.emit('sendmessage', 'hi');
```

And I get the following error in the console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<app_id>.execute-api.<region>.amazonaws.com/socket.io/?EIO=4&transport=polling&t=NZM3Y0O. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

How can I add CORs support to the API Gateway Websocket? I cannot find any information on this.

**Comment by code-wizard** [comment]
@paul-uz  how did you resolve this issue?

**Comment by paul-uz** [comment]
I believe the issue was that Socket.io does not work with API Gateway Websockets and I had to test using wscat in the CLI
