### ISSUE TITLE
This template no longer works

### ISSUE THREAD

**Issue by genifycom** [aws-samples/simple-websockets-chat-app#56]
The deployment fails with:

"Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 0cfaea73-519e-4c9e-a57d-f983a2e2c252)" (RequestToken: 5b6cfae8-94b7-745c-c31d-f7029c02e83d, HandlerErrorCode: InvalidRequest)"

**Comment by dgomesbr** [comment]
Just updated to the latest and deployed successfully. Let me know if it fix on your end.
