### ISSUE TITLE
Client sample

### ISSUE THREAD

**Issue by mrahman4** [aws-samples/simple-websockets-chat-app#6]
Can we enrich this sample by adding client code. So we can see how client will receive messages

**Comment by dgomesbr** [comment]
Hello @mrahman4, the discussed piece is shown with `wscat` on the [blog post here](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/); 

Is there something particular do you want to be added on the repo?

**Comment by stinson7** [comment]
Slightly off topic, but could you add some information about how the lambda functions are attached to routes in the Api Gateway. As far as I understand for this example the SAM template only creates the functions, the user will still have to manually attach the sendmessage, onconnect, and ondisconnect functions to the route using the Api Gateway console. I am just learning how to use SAM but this was not immediately clear and I spent a lot of time staring at the template.yaml trying to figure out how Api Gateway endpoints were created.

**Comment by dgomesbr** [comment]
Hey @stinson7, the blog post explains that this is just foundational code.
Until SAM, and therefore cloudformation, supports WebSocket on API Gateway,
we have no way of automatically wire everything end-to-end.

**Comment by dgomesbr** [comment]
@stinson7 CFn is now live. Template update: https://aws.amazon.com/about-aws/whats-new/2019/02/automate-websocket-api-creation-in-api-gateway-with-cloudformation/

**Comment by armujahid** [comment]
Client samples mentioned in [blog](https://aws.amazon.com/blogs/compute/announcing-websocket-apis-in-amazon-api-gateway/) are no longer valid.

1. In blog we have `$request.body.action` as route selection expression while latest code in this repo has `$request.body.message` as route selection expression. 
2. Correct route for message sending is `sendMessage`, not `sendmessage` as mentioned in blog post.

![image](https://user-images.githubusercontent.com/3725386/55247586-d760cd80-5269-11e9-8c4b-425f422b7458.png)

PS: Ignore internal server error issue. I have logged it separately at https://github.com/aws-samples/simple-websockets-chat-app/issues/18

**Comment by tomellis** [comment]
Thanks @armujahid that helped me whilst running this today.
Had to craft my message to be (also left a comment on the blog which will appear once approved):
{"message":"sendMessage", "data":"hello world"}
