### ISSUE TITLE
Why are you adding ApiGatewayManagementApi?

### ISSUE THREAD

**Issue by tverbiscer** [aws-samples/simple-websockets-chat-app#8]
Why are you doing the following?

    // Add ApiGatewayManagementApi to the AWS namespace
    require('aws-sdk/clients/apigatewaymanagementapi');

**Comment by jt0** [comment]
There's a lag between when a new (or update to an existing) SDK makes its way into the Lambda-provided NodeJS runtime.  This is a temporary "fix" to provide the SDK until it becomes available. 

Thanks for asking!
