### ISSUE TITLE
Cloudformation Template for API Gateway WebSocket?

### ISSUE THREAD

**Issue by JoseRolles** [aws-samples/simple-websockets-chat-app#9]
Do Cloudformation templates currently support automatically creating API Gateway for WebSockets type and NOT REST type?

**Comment by dgomesbr** [comment]
Hello @JoseRolles, the API Gateway team is working in providing the support for CFn.

**Comment by dgomesbr** [comment]
@JoseRolles CFn is now live. Template update: https://aws.amazon.com/about-aws/whats-new/2019/02/automate-websocket-api-creation-in-api-gateway-with-cloudformation/

**Comment by JoseRolles** [comment]
Awesome! Thanks.

**Comment by FreFre** [comment]
There is no support yet for integration type VPC link for API V2/websocket using Cloudformation?
It can be achieved manually using the AWS Console.

**Comment by mateo-sierra-cloud** [comment]
can i host this settings in a vpc?, when i host my lambda in public subnet and igw attached vpc, i doesnt respond back, any sugestions?

**Comment by JoseRolles** [comment]
Unfortunately, Lambda inside VPC public subnet cannot access the internet and will require running a NAT. Please see this answer for more details: https://stackoverflow.com/a/52994841
